### ISSUE TITLE
mysql dependency broken

### ISSUE THREAD

**Issue by jplord166** [mariancerny/freebsd-ports-php56#1]
In your README.md:
## Testing

Tested on FreeBSD 11.2 and 12.0 with main FreeBSD ports tree from May 2019.

It may break in a future version of the main FreeBSD ports tree. Hopefully, it will last for some time.

Sadly, "for some time" lasted until May 24, 2019, when they removed the mysql_DEPENDS line from /usr/ports/MK/Uses/php.mk file.  pdo_mysql now bombs on build with:

Error: bad dependency syntax in RUN_DEPENDS
expecting: pattern:origin[@flavour][:target]
got: /usr/local/lib/php/20131226-debug/mysql.so:
Errors with dependencies.

I just added the following line:
mysql_DEPENDS=  databases/php${PHP_VER}-mysql
to /usr/local/ports/php56/databases/php56-pdo_mysql/Makefile and it built fine.

**Comment by mariancerny** [comment]
I have just build today our selection of php56 ports without any issues. Including `php56-pdo_mysql`.
Did you check the [Caveats](https://github.com/mariancerny/freebsd-ports-php56#caveats) section in README.md? Especially:

> You must install databases/php56-pdo manually before installing databases/php56-pdo_mysql.

I am also installing `databases/php56-mysql` before.

**Comment by jplord166** [comment]
Yes, I followed those instructions carefully.  php56-pdo and php56-mysql were both installed prior to php56-pdo_mysql.  php56-pdo_mysql would not build until I modified the Makefile.

The change that should have broken your build (and did break mine) is documented here:
https://www.freshports.org/Mk/Uses/php.mk

**Comment by mariancerny** [comment]
Sorry, I did not realize I have already dealt with this issue in my setup. I forgot to commit and push the changes.
I have added `mysql_DEPENDS` into `/etc/make.conf`.
Thanks for the report!
