### ISSUE TITLE
Compiled PHP 5.6 Extensions on FreeBSD 13.1

### ISSUE THREAD

**Issue by rwp0** [mariancerny/freebsd-ports-php56#10]
I've managed to compile many PHP extensions (PERL and standard) on FreeBSD 13.1 and use it for running websites successfully.

Among them are Memcache, Memcached, PHAR, SSH2, and so on.

@mariancerny  do you think I should submit pull requests of those `.so` files with `.ini` extensions, and a `README` in the directory with instructions on where to download, how to compile, and install since it can help many users using this repository?

Also if you're not maintaining this repository anymore, could you move it under a common GitHub organization or else transfer it to my GitHub user so that I can take from there and do that myself.

Thanks

**Comment by mariancerny** [comment]
I have added you as a contributor, so you should be able to commit directly.

**Comment by rwp0** [comment]
@mariancerny awesome, thanks!

**Comment by mariancerny** [comment]
I have moved your changes to `rwp0` branch. I don't think binary files are a good fit for the repository.
