### ISSUE TITLE
Add pecl-APCu4

### ISSUE THREAD

**Issue by GreenReaper** [mariancerny/freebsd-ports-php56#2]
I suggest adding the port [devel/pecl-APCu4](https://www.freshports.org/devel/pecl-APCu4) which is helpful for caching of user data in combination with opcache (vs. APC). [The shell archive here](https://bz-attachments.freebsd.org/attachment.cgi?id=179834) (extractable in devel with `sh [filename]) contains a copy.

**Comment by mariancerny** [comment]
Thanks for suggestion. I have noticed that this port has been already added in a fork (https://github.com/guggemand/freebsd-ports-php56/commit/c45cde9a6c3757b24bbf6b0b21f67e0f5b474ec9), so I have merged that change. This should be fixed now.
