### ISSUE TITLE
Hint: recommend unionfs

### ISSUE THREAD

**Issue by TLINDEN** [mariancerny/freebsd-ports-php56#5]
Howdy,

in your README you write, that dependencies have to be built manually. However, if you mount the repository using unionfs onto `/usr/ports` then all dependencies build automatically just fine.

Eg:
```
mount -t unionfs -o ro $HOME/git/freebsd-ports-php56 /usr/ports
```

Other than that: thanks for the effort, helps a lot!

Tom

**Comment by mariancerny** [comment]
Thanks for the suggestion. I have updated the README.md to include this.
