### ISSUE TITLE
Unknown extension xxx for PHP56

### ISSUE THREAD

**Issue by cro888888** [mariancerny/freebsd-ports-php56#6]
As the title is, installation of php56-extensions and php56-pdo_mysql installation encountered this problem and likely more.

pdo.so is found in `/usr/local/lib/php/20131226-zts/`
extension ini files(not extensions.ini) are found in `/usr/local/etc/php`

Message from `make install` of php56-pdo:
```
===>  Installing for php56-pdo-5.6.40
===>  Checking if php56-pdo is already installed
===>   Registering installation for php56-pdo-5.6.40
Installing php56-pdo-5.6.40...
This file has been added to automatically load the installed extension:
/usr/local/etc/php/ext-20-pdo.ini
===>   NOTICE:

This port is deprecated; you may wish to reconsider installing it:

Security Support ends on 31 Dec 2018.

It is scheduled to be removed on or after 2019-01-01.
```

Output from `make install` of php56-pdo_mysql:

```
Unknown extension pdo for PHP 56.
*** Error code 1

Stop.
make[1]: stopped in /home/cro/php56/databases/php56-pdo_mysql
*** Error code 1
```

Same for php56-extensions, if I `make config` and uncheck everything it works. otherwise it gives me error for every single extension I checked.

`uname -a`:
`FreeBSD 11.3-RELEASE-p2 FreeBSD 11.3-RELEASE-p2 #0: Tue Aug  6 05:07:20 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`

**Comment by mariancerny** [comment]
You need to add some variables to `/etc/make.conf` as described in the README. See https://github.com/mariancerny/freebsd-ports-php56#preparation
